Repository vegaprotocol/frontend-monorepo, pull requests merged in 2022-11, with the labels that each got.

#1908 chore: remove duplicated addDecimal function
  apps/token-e2e/src/integration/flow/staking-flow.cy.js
  apps/token/src/components/vega-wallet/hooks.ts
  apps/token/src/lib/apollo-client.ts
  apps/token/src/lib/decimals.test.ts
  apps/token/src/lib/decimals.ts
  apps/token/src/routes/claim/claim-reducer.ts
  apps/token/src/routes/staking/node/pending-stake.tsx
  apps/token/src/routes/staking/node/staking-form.tsx
Labels: Token Frontend

#1934 fix(#1883): fix depth chart not updating
  libs/market-depth/src/lib/depth-chart.tsx
Labels: Trading

#2095 chore: separate running vegawallet service out of vegacapsule
  .github/actions/setup-vegawallet-docker/action.yml
  .github/actions/setup-vegawallet/action.yml
  .github/workflows/cypress-console-lite-e2e.yml
  .github/workflows/cypress-explorer-e2e.yml
  .github/workflows/cypress-token-e2e.yml
  .github/workflows/cypress-trading-e2e.yml
  vegacapsule/config.hcl
  vegacapsule/recovery
  vegacapsule/wallet-config.toml
Labels: Testing 🧪, common

#2242 chore: add regression tagged tests to PR runs
  .github/workflows/capsule-cypress.yml
  apps/explorer-e2e/src/integration/parties.cy.js
  apps/trading-e2e/src/integration/trading-deal-ticket.cy.ts
  apps/trading-e2e/src/integration/trading-portfolio.cy.ts
  libs/deal-ticket/src/hooks/use-order-margin.ts
Labels: Testing 🧪, common
