Repository vegaprotocol/frontend-monorepo, pull requests merged in 2022-07, with the labels that each got.

#771 chore: remove GOPROXY
  .github/workflows/capsule-cypress-nightly.yml
  .github/workflows/capsule-cypress.yml
Labels: KTLO

#830 Fix/withdrawal max
  apps/trading-e2e/src/integration/deposit.cy.ts
  apps/trading-e2e/src/integration/withdraw.cy.ts
  libs/deposits/src/lib/deposit-form.spec.tsx
  libs/deposits/src/lib/deposit-form.tsx
  libs/deposits/src/lib/deposit-limits.tsx
  libs/deposits/src/lib/deposit-manager.tsx
  libs/withdraws/src/lib/use-get-withdraw-limits.tsx
  libs/withdraws/src/lib/withdraw-form.spec.tsx
  libs/withdraws/src/lib/withdraw-form.tsx
  libs/withdraws/src/lib/withdraw-limits.tsx
  libs/withdraws/src/lib/withdraw-manager.spec.tsx
  libs/withdraws/src/lib/withdraw-manager.tsx
Labels: Trading, Token Frontend

#883 test: fix staking functions and association tests
  apps/token-e2e/src/integration/flow/staking-flow.cy.js
  apps/token-e2e/src/integration/flow/token-association-flow.cy.js
  apps/token-e2e/src/support/wallet-teardown.functions.js
Labels: Testing 🧪, Token Frontend

#906 Remove nightly runs
  .github/workflows/capsule-cypress-nightly copy.yml
  .github/workflows/capsule-cypress-nightly.yml
Labels: Testing 🧪

#917 test: add night runs again
  .github/workflows/capsule-cypress-night-run.yml
Labels: Testing 🧪
